# nginx.conf
events {}
http {
    upstream anz_agent {
        server app-1:8000 max_fails=2 fail_timeout=10s;
        server app-2:8000 max_fails=2 fail_timeout=10s;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://anz_agent;
            proxy_set_header Host $host;
            proxy_read_timeout 300s;
            proxy_send_timeout 300s;
        }
    }
}
